export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_POST_STATE_CHANGE = "USER_POST_STATE_CHANGE";
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";
export const ALL_USERS_POST_STATE_CHANGE = "ALL_USERS_POST_STATE_CHANGE";
export const ALL_USERS_STATE_CHANGE = "ALL_USERS_STATE_CHANGE";
export const CLEAR_DATA = "CLEAR_DATA";

export const ALL_USERS_LIKE_STATE_CHANGE = "ALL_USERS_LIKE_STATE_CHANGE";
